#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo "http://localhost/local/default.git"

strains:
  - name: default
    code: https://github.com/kptdobe/helix-preview.git#master
    content: https://github.com/kptdobe/helix-preview.git#master
    static: https://github.com/kptdobe/helix-preview.git/htdocs#master
    package: 40772f69db018ba4a72ca869f7023ffd7a169133
  - name: dev
    url: http://localhost:3000/
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo
