#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    # default repository. set to git remote repository before deployment
    - &defaultRepo "http://localhost/local/default.git"

strains:
  default:
    code: https://github.com/kptdobe/helix-preview.git#master
    content: https://github.com/kptdobe/helix-preview.git#master
    static: https://github.com/kptdobe/helix-preview.git/htdocs#master
    package: 8fa10ed9a3434a0f8f1b9837d2fad22096bbc97e
